language: cpp
dist: xenial

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - llvm-8-dev
    - bison
    - flex

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ./compiler/compiler_tests